"""добавил в пользователей about

Revision ID: 00334525670a
Revises: 4f54335b3b04
Create Date: 2023-04-22 11:39:55.333772

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00334525670a'
down_revision = '4f54335b3b04'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('about', sa.String(length=140), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'about')
    op.alter_column('posts', 'post_tg_url',
               existing_type=sa.NUMERIC(),
               nullable=False)
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.create_foreign_key(None, 'comments', 'users', ['author_id'], ['id'])
    # ### end Alembic commands ###
