"""добавил порядок для постов

Revision ID: ad1b0b92eac7
Revises: 27ae0f11a8ae
Create Date: 2023-04-15 14:42:36.247950

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad1b0b92eac7'
down_revision = '27ae0f11a8ae'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
